### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by coderextreme** [redaktor/owl2jsonschema.js#2]
Please add a license

**Comment by akuckartz** [comment]
:+1: The software is not usable without a license.

**Comment by coderextreme** [comment]
If it’s in a public repository on GitHub, it better have an open source license.  Otherwise, you should be spending money hosting.

John

**Comment by sebilasse** [comment]
@coderextreme @akuckartz 
preclaimer : This is in an experimental state and I clearly wrote it is a "WIP".
The general problem is that you will never be able to translate OWL to JSON Schema 1:1.
So I started this to check out what would be the closest "translation"...
However - I added a LICENSE now.
